[package]
name = "marathon592"
version = "0.1.0"
authors = ["balasopandr"]
edition = "2018"

[lib]
name="math"
path="libs/math.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
