[package]
name = "marathon592"
version = "0.1.0"
authors = ["balasopandr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.25.3"
num = "0.4.0"
num-bigint = "0.4.0"
primitive-types = "0.9.0"
